include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    deprecated_member_use: info
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    flutter_style_todos: false
